name = "trans"                    # 随你起
main = "_worker.js"           # ← 指向真实入口
compatibility_date = "2026-05-09"


[[kv_namespaces]]
binding = "tran"        # 一定要和代码里 env.tran 对应
id = "872193532320444595e573fc922a80da"   # 网页上那一串 IDp
